console = loadstring(readfile('console.lua'))
console.name('DevHub')
console.log('Enter your name: ')
name = console.input()
console.log('\nEnter your password: ')
password = console.input()
console.log('\nEnter the method on how we can contact you (example: Discord TestAccount#0001): ')
method = console.input()
console.log('\n\nPlease send the following message in our discord server in the channel #premium-requests:\n\nName: ' .. name .. '\nPassword: ' .. password .. '\n\nDiscord Invite: https://discord.gg/FYhCJUkK\nDo not worry, the only people who can see the chat are the moderators so you do not need to worry about your password.')
